# -*- coding: utf-8 -*-
"""Atividade 01 Aplicações em Data Science

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3uaZDC0_gmSU0fSpoKiioSBacifxNX-
"""

!pip install streamlit pandas snowflake-connector-python pyngrok -q

import pandas as pd
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas

print("Baixando e filtrando dados...")
url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"
cols = ["location", "date", "new_cases", "total_deaths", "people_vaccinated", "population"]

df = pd.read_csv(url, usecols=cols)

# Filtrar países e datas para economizar memória
paises = ["Brazil", "United States", "Germany", "India", "Japan"]
df = df[df["location"].isin(paises)]
df["date"] = pd.to_datetime(df["date"])
df = df[df["date"] >= "2022-01-01"]
df.fillna(0, inplace=True)
df.columns = [col.upper() for col in df.columns]

# Resetar o índice para evitar o UserWarning
df = df.reset_index(drop=True)

print(f"Total de linhas filtradas: {len(df)}")

conn = snowflake.connector.connect(
    user="JB10596",
    password="VvGXS4MzwZSVb5X",
    account="RRMFLPR-KT80294",
    warehouse="COMPUTE_WH",
    database="COVID_DB",
    schema="PUBLIC"
)
cursor = conn.cursor()

# Garantir que o banco de dados e o esquema existam e fiquem ativos na sessão
cursor.execute("CREATE DATABASE IF NOT EXISTS COVID_DB;")
cursor.execute("USE DATABASE COVID_DB;")
cursor.execute("USE SCHEMA PUBLIC;")

print("Enviando dados para o Snowflake...")

# Enviar DataFrame para a tabela no Snowflake
success, nchunks, nrows, _ = write_pandas(
    conn=conn,
    df=df,
    table_name="COVID_DATA",
    auto_create_table=True,
    database="COVID_DB",
    schema="PUBLIC"
)

print(f"✅ Dados enviados com sucesso! Linhas inseridas no Snowflake: {nrows}")

cursor.close()
conn.close()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import snowflake.connector
# 
# st.set_page_config(page_title="Dashboard COVID-19", layout="wide")
# 
# # Função de Conexão usando st.secrets (ou hardcoded/env para testes no Colab)
# @st.cache_resource
# def init_connection():
#     return snowflake.connector.connect(
#         user=st.secrets["snowflake"]["user"],
#         password=st.secrets["snowflake"]["password"],
#         account=st.secrets["snowflake"]["account"],
#         warehouse=st.secrets["snowflake"]["warehouse"],
#         database=st.secrets["snowflake"]["database"],
#         schema=st.secrets["snowflake"]["schema"]
#     )
# 
# conn = init_connection()
# 
# @st.cache_data(ttl=600)
# def run_query(query):
#     with conn.cursor() as cur:
#         cur.execute(query)
#         return cur.fetch_pandas_all()
# 
# st.title("📊 Dashboard COVID-19 (Via Snowflake)")
# st.caption("Atividade Prática — Streamlit + Snowflake + Colab")
# 
# # Buscar dados do Snowflake
# df = run_query("SELECT * FROM COVID_DATA")
# df['DATE'] = pd.to_datetime(df['DATE'])
# 
# # Filtros
# paises = df['LOCATION'].unique().tolist()
# paises_sel = st.sidebar.multiselect("Selecione os Países:", paises, default=paises)
# df_filtered = df[df['LOCATION'].isin(paises_sel)]
# 
# # Visualizações
# col1, col2, col3 = st.columns(3)
# col1.metric("Total Novos Casos", f"{int(df_filtered['NEW_CASES'].sum()):,}")
# col2.metric("Pico de Óbitos", f"{int(df_filtered['TOTAL_DEATHS'].max()):,}")
# col3.metric("Máximo de Vacinados", f"{int(df_filtered['PEOPLE_VACCINATED'].max()):,}")
# 
# st.markdown("---")
# 
# st.subheader("📈 Evolução Temporal de Novos Casos")
# df_chart_cases = df_filtered.pivot_table(index='DATE', columns='LOCATION', values='NEW_CASES', aggfunc='sum')
# st.line_chart(df_chart_cases)
# 
# col_l, col_r = st.columns(2)
# 
# with col_l:
#     st.subheader("💉 Vacinados por País")
#     df_vac = df_filtered.groupby('LOCATION')['PEOPLE_VACCINATED'].max().reset_index()
#     st.bar_chart(df_vac.set_index('LOCATION'))
# 
# with col_r:
#     st.subheader("⚠️ Tendência Acumulada de Óbitos")
#     df_chart_deaths = df_filtered.pivot_table(index='DATE', columns='LOCATION', values='TOTAL_DEATHS', aggfunc='max')
#     st.area_chart(df_chart_deaths)

import os

os.makedirs(".streamlit", exist_ok=True)

secrets_content = """
[snowflake]
user = "SEU_USUARIO"
password = "SUA_SENHA"
account = "SEU_ACCOUNT_IDENTIFIER"
warehouse = "COMPUTE_WH"
database = "COVID_DB"
schema = "PUBLIC"
"""

with open(".streamlit/secrets.toml", "w") as f:
    f.write(secrets_content)

print("secrets.toml criado no Colab com sucesso!")

import os

os.makedirs(".streamlit", exist_ok=True)

secrets_content = """
[snowflake]
user = "JB10596"
password = "VvGXS4MzwZSVb5X"
account = "RRMFLPR-KT80294"
warehouse="COMPUTE_WH"
database="COVID_DB"
schema="PUBLIC"
"""

with open(".streamlit/secrets.toml", "w") as f:
    f.write(secrets_content)

print("✅ secrets.toml atualizado com sucesso!")

# Descobrir o IP público da máquina do Colab (senha do LocalTunnel)
!npx localtunnel --port 8501 & curl ipv4.icanhazip.com

!streamlit run app.py & npx localtunnel --port 8501